In [21]:
import numpy as np
import pandas as pd

resp = np.array([[0.55802307, 0.40857575, 0.03340118],
                 [0.74859379, 0.20161706, 0.04978915],
                 [0.73547618, 0.19266626, 0.07185756],
                 [0.86730087, 0.07896252, 0.05373661],
                 [0.87337118, 0.05888063, 0.06774819]])         

new_resp = np.array([[0.55802307, 0.40857575, 0.        ],
                     [0., 0., 0.        ],
                     [0.73547618, 0.19266626, 0.        ],
                     [0.86730087, 0.,         0  ],
                     [0.87337118, 0.,        0.0 ]])

# print(new_resp)

#Start of donate function
temp_resp=new_resp.copy()
# print("temp_resp before :\n", temp_resp)
#change all the value > 0 in temp_resp to 1 for calculation purpose
temp_resp[temp_resp > 0] = 1
# print("temp_resp before  :\n", temp_resp)
# print("resp before: \n ", resp)

#Remove all rows with the same index where all temp_resp values = 0
# resp = resp[~np.all(temp_resp == 0, axis=1)]
# temp_resp = temp_resp[~np.all(temp_resp == 0, axis=1)]

print("temp_resp after: \n", temp_resp)
print("resp after: \n ", resp)

n_sample,k_cluster  = temp_resp.shape
print(n_sample,k_cluster)
for i in range(n_sample):
    mul_resp=0
    sum_resp=0
    mul_resp = np.multiply(resp[i],temp_resp[i])
    print(mul_resp)
   
    sum_resp = sum(np.multiply(resp[i],temp_resp[i]))
    print(sum_resp)
    if (np.count_nonzero(temp_resp[i])==0):
        temp_resp[i] = 0
    else:
        temp_resp[i] = mul_resp/sum_resp
        print(temp_resp[i])
   

# print(new_resp,"\n")
# print(temp_resp,"\n")

# print("Alhamdulillah...Thank You Allah!") 
        

temp_resp after: 
 [[1. 1. 0.]
 [0. 0. 0.]
 [1. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
resp after: 
  [[0.55802307 0.40857575 0.03340118]
 [0.74859379 0.20161706 0.04978915]
 [0.73547618 0.19266626 0.07185756]
 [0.86730087 0.07896252 0.05373661]
 [0.87337118 0.05888063 0.06774819]]
5 3
[0.55802307 0.40857575 0.        ]
0.96659882
[0.57730576 0.42269424 0.        ]
[0. 0. 0.]
0.0
[0.73547618 0.19266626 0.        ]
0.92814244
[0.79241736 0.20758264 0.        ]
[0.86730087 0.         0.        ]
0.86730087
[1. 0. 0.]
[0.87337118 0.         0.        ]
0.87337118
[1. 0. 0.]


In [13]:
import numpy as np

a = np.array([
    [1, 0, 0],
    [0, np.nan, 0],
    [0, 0, 0],
    [np.nan, np.nan, np.nan],
    [2, 3, 4]
])

mask = np.all(np.isnan(a) ,axis=1)
a[~mask]

(5, 3)


array([1., 0., 0., 0., 0., 0., 0., 0., 2., 3., 4.])

In [ ]:
from IPython.core.display import display, HTML
display(HTML("<style>div.output_scroll { height: 44em; }</style>"))

In [ ]:
a1 = [1, 2, 1]
a2 = [2, 2, 3]
print (sum(np.multiply(a1, a2)))

In [ ]:

# # Create an empty list
# filter_new_resp = []
# arr = np.array([[1, 2, 3], [4, 5, 6]])



# for x in new_resp:
#     print(x)
#     for y in x:
#         if y==0:
#             new_resp_zero.append(x)
#         else:
#             new_resp_x_zero.append(x)

# print(new_resp_zero)
# print(new_resp_x_zero)
        
# arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# new_resp_zero = []
# new_resp_x_zero = []
# for idx, x in np.ndenumerate(new_resp):
#     if x==0:
# #         print("x==0:",idx)
# #         print(new_resp.item(idx))
#         new_resp_zero.append(idx)
#     else:
# #         print("x!=0:",idx)
# #         print(new_resp.item(idx))
#         new_resp_x_zero = new_resp_x_zero, idx
        
# print(new_resp_zero)
# print(new_resp_x_zero)


new_resp_x_zero =[]
final_resp = new_resp.copy()
for x in new_resp:
#     print(x)  
    np_x_zero = np.nonzero(x)[i] 
    new_resp_x_zero += [np_x_zero]
    
print(new_resp_x_zero)
    

# for i in range(len(new_resp_x_zero)):
#     for j in range(len(new_resp_x_zero[i])):
#         if len(new_resp_x_zero[i]) == 1:
#             print(i, " : ", j)
#             new_resp.item((j,i)) = 1
#         else:
#             print("done")




In [ ]:
new_resp_zero = []
new_resp_x_zero = []
for idx, x in np.ndenumerate(new_resp):
    if x==0:
#         print("x==0:",idx)
#         print(new_resp.item(idx))
        new_resp_zero.append(idx)
    else:
#         print("x!=0:",idx)
#         print(new_resp.item(idx))
        new_resp_x_zero.append(idx)
        
# print(new_resp_zero)
print(new_resp_x_zero)

for idx in new_resp_x_zero:
#     print(idx)
    if idx[0]==0  :
        print(new_resp.item(idx))
    

In [ ]:
new_resp_zero = []
new_resp_x_zero = []
for idx, x in np.ndenumerate(new_resp):
    for i in range (len(new_resp)):
        if x == 0:
#           
            new_resp_zero = (idx)
            
        else:
            print("idx : ",idx)
            resp_x_zero = idx
            
  
            
    
#     new_resp_zero += [idx]
#     print(new_resp_zero)
#     print(idx[0])
    
#     if x==0:
# # #         new_resp_zero.append(idx)
#         np_zero = (idx)
#         new_resp_zero += np_zero
#         print(x)
#         print("new_resp_zero : ",new_resp_zero)
        
#     else:
# #         new_resp_zero.append(idx)
#         np_x_zero = np.array(idx)
#         new_resp_x_zero += [np_x_zero]
# #         print(new_resp_x_zero)

       

In [ ]:
test_arr = np.array([[[0,1],[0,2]], [[1,1],[1,2]]])


In [ ]:
print(len(new_resp[0]))
print(new_resp[0,1])
print(new_resp.item(0,1))

In [ ]:

for i in range(np.size(new_resp, 0)):
    
    #check if only one new-resp is non zero 
    if (len(new_resp_x_zero[i])) == 1:
        resp.item((idx) = 1
    else:
        
                  
                  
        
#         for j in range (np.size(new_resp, 1)):
              
#             print(new_resp_x_zero[i])
# #         print(new_resp((i)))
#         print(new_resp.item((i, j)))
